In [1]:
# Import required libraries
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("healthcare-dataset-stroke-data.csv")

# Check dataset shape
print("Dataset shape:", df.shape)

# Preview first rows
df.head()

Dataset shape: (5110, 12)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [2]:
# Display column names, data types, and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [3]:
# Count duplicate rows
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

# Display duplicate rows if they exist
if duplicate_count > 0:
    duplicate_rows = df[df.duplicated(keep=False)]
    display(duplicate_rows)

Number of duplicate rows: 0

In [4]:
# Count missing values per column
null_values = df.isna().sum()
print("Missing values per column:\n")
print(null_values[null_values > 0])

# Display rows containing at least one missing value
rows_with_nulls = df[df.isna().any(axis=1)]
print("\nRows containing missing values:", rows_with_nulls.shape[0])
display(rows_with_nulls.head(10))

Missing values per column:

bmi    201
dtype: int64

Rows containing missing values: 201

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
8,27419,Female,59.0,0,0,Yes,Private,Rural,76.15,NaN,Unknown,1
13,8213,Male,78.0,0,1,Yes,Private,Urban,219.84,NaN,Unknown,1
19,25226,Male,57.0,0,1,No,Govt_job,Urban,217.08,NaN,Unknown,1
27,61843,Male,58.0,0,0,Yes,Private,Rural,189.84,NaN,Unknown,1
29,69160,Male,59.0,0,0,Yes,Private,Rural,211.78,NaN,formerly smoked,1
43,1845,Female,63.0,0,0,Yes,Private,Urban,90.90,NaN,formerly smoked,1
46,37937,Female,75.0,0,1,No,Self-employed,Urban,109.78,NaN,Unknown,1
50,18587,Female,76.0,0,0,No,Private,Urban,89.96,NaN,Unknown,1
51,15102,Male,78.0,1,0,Yes,Private,Urban,75.32,NaN,formerly smoked,1

In [5]:
# Identify categorical columns
categorical_cols = df.select_dtypes(include="object").columns

# Remove leading/trailing spaces from text data
for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip()

# Verify unique values count after cleaning
df[categorical_cols].nunique()

gender            3
ever_married      2
work_type         5
Residence_type    2
smoking_status    4
dtype: int64

In [6]:
# Convert 'Unknown' smoking status to NaN
df["smoking_status"] = df["smoking_status"].replace("Unknown", np.nan)

# Check how many values became missing
print("Missing smoking_status values:", df["smoking_status"].isna().sum())

# Display affected rows
display(df[df["smoking_status"].isna()].head(10))

Missing smoking_status values: 1544

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
8,27419,Female,59.0,0,0,Yes,Private,Rural,76.15,NaN,NaN,1
9,60491,Female,78.0,0,0,Yes,Private,Urban,58.57,24.2,NaN,1
13,8213,Male,78.0,0,1,Yes,Private,Urban,219.84,NaN,NaN,1
19,25226,Male,57.0,0,1,No,Govt_job,Urban,217.08,NaN,NaN,1
23,64778,Male,82.0,0,1,Yes,Private,Rural,208.30,32.5,NaN,1
27,61843,Male,58.0,0,0,Yes,Private,Rural,189.84,NaN,NaN,1
31,33879,Male,42.0,0,0,Yes,Private,Rural,83.41,25.4,NaN,1
38,47306,Male,58.0,0,0,No,Private,Rural,92.62,32.0,NaN,1
46,37937,Female,75.0,0,1,No,Self-employed,Urban,109.78,NaN,NaN,1
50,18587,Female,76.0,0,0,No,Private,Urban,89.96,NaN,NaN,1

In [7]:
# Check missing BMI values before imputation
print("Missing BMI before:", df["bmi"].isna().sum())

# Fill missing BMI with median value
df["bmi"] = df["bmi"].fillna(df["bmi"].median())

# Check missing BMI values after imputation
print("Missing BMI after:", df["bmi"].isna().sum())

Missing BMI before: 201
Missing BMI after: 0

In [8]:
# Check missing smoking status before filling
print("Missing smoking_status before:", df["smoking_status"].isna().sum())

# Fill missing smoking status using most frequent value (mode)
df["smoking_status"] = df["smoking_status"].fillna(df["smoking_status"].mode()[0])

# Verify result
print("Missing smoking_status after:", df["smoking_status"].isna().sum())

Missing smoking_status before: 1544
Missing smoking_status after: 0

In [9]:
# Drop ID column as it has no predictive value
if "id" in df.columns:
    df = df.drop(columns=["id"])

print("Shape after dropping ID column:", df.shape)

Shape after dropping ID column: (5110, 11)

In [10]:
# Final check for missing values
print("Remaining missing values:\n", df.isna().sum())

# Final duplicate check
print("Remaining duplicate rows:", df.duplicated().sum())

# Preview cleaned dataset
df.head()

Remaining missing values:
 gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64
Remaining duplicate rows: 0

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1